### ISSUE TITLE
Doesn't seem to work work with Netbeans Dev? (8.2?)

### ISSUE THREAD

**Issue by cyraid** [matthiasblaesing/netbeans-mantis-integration#29]
Hi there, like the subject suggests.. I can refresh Tasks in 8.1 but can't seem to open tasks from query in 8.2.. (using the list in the tasks area)

`java.lang.NullPointerException
	at eu.doppel_helix.netbeans.mantisintegration.issue.MantisScheduleProvider.getSchedule(MantisScheduleProvider.java:122)
	at eu.doppel_helix.netbeans.mantisintegration.issue.MantisScheduleProvider.getSchedule(MantisScheduleProvider.java:18)
	at org.netbeans.modules.bugtracking.IssueImpl.getSchedule(IssueImpl.java:292)
	at org.netbeans.modules.bugtracking.tasks.DashboardUtils.isAfterDue(DashboardUtils.java:400)
	at org.netbeans.modules.bugtracking.tasks.DashboardUtils.getScheduleIndex(DashboardUtils.java:376)
	at org.netbeans.modules.bugtracking.tasks.TaskSorter$ScheduleComparator.compare(TaskSorter.java:182)
	at org.netbeans.modules.bugtracking.tasks.TaskSorter$ScheduleComparator.compare(TaskSorter.java:178)
	at org.netbeans.modules.bugtracking.tasks.TaskAttribute.compare(TaskAttribute.java:79)
	at org.netbeans.modules.bugtracking.tasks.TaskSorter$TaskComparator.compare(TaskSorter.java:102)
	at org.netbeans.modules.bugtracking.tasks.TaskSorter$TaskComparator.compare(TaskSorter.java:97)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at org.netbeans.modules.bugtracking.tasks.dashboard.TaskContainerNode.createChildren(TaskContainerNode.java:324)
	at org.netbeans.modules.team.commons.treelist.TreeListNode$ChildrenLoader$1.run(TreeListNode.java:367)
[catch] at java.lang.Thread.run(Thread.java:745)`

**Comment by matthiasblaesing** [comment]
I can reproduce this problem if no custom field is defined. I'll look into this. In the meantime please install the client version 1.3. The problematic change was introduced in the 1.4 cycle.

**Comment by matthiasblaesing** [comment]
Ok - I pushed a potential fix - could you test this version:

https://github.com/matthiasblaesing/netbeans-mantis-integration/wiki/MantisIntegration-1.4.1-SNAPSHOT.nbm

Thank you!

**Comment by cyraid** [comment]
Beautiful! You're the man, Matthias.
