### ISSUE TITLE
No success with 2.12.0

### ISSUE THREAD

**Issue by Madir123** [matthiasblaesing/netbeans-mantis-integration#36]
I try to install this pulgin for the first time. At the beginning I had problems with the SSL Certificate but I handled this as mentioned in the README. But still I'm not able to connect.

This is the IDE Log:
`org.xml.sax.SAXParseException;` lineNumber: 1; columnNumber: 1; Content ist nicht zulässig in Prolog.
	at org.apache.axis.AxisFault.makeFault(AxisFault.java:101)
	at org.apache.axis.SOAPPart.getAsSOAPEnvelope(SOAPPart.java:701)
	at org.apache.axis.Message.getSOAPEnvelope(Message.java:435)
	at org.apache.axis.handlers.soap.MustUnderstandChecker.invoke(MustUnderstandChecker.java:62)
	at org.apache.axis.client.AxisClient.invoke(AxisClient.java:206)
	at org.apache.axis.client.Call.invokeEngine(Call.java:2784)
	at org.apache.axis.client.Call.invoke(Call.java:2767)
	at org.apache.axis.client.Call.invoke(Call.java:2443)
	at org.apache.axis.client.Call.invoke(Call.java:2366)
	at org.apache.axis.client.Call.invoke(Call.java:1812)
	at biz.futureware.mantisconnect.MantisConnectBindingStub.mc_projects_get_user_accessible(MantisConnectBindingStub.java:2937)
	at eu.doppel_helix.netbeans.mantisintegration.repository.MantisRepository.checkConnection(MantisRepository.java:141)
	at eu.doppel_helix.netbeans.mantisintegration.repository.MantisRepositoryController$2.doInBackground(MantisRepositoryController.java:276)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

Please give me an advice how to solve this.

**Comment by matthiasblaesing** [comment]
This looks like the API is disabled/not present.
