### ISSUE TITLE
Cant add a repository

### ISSUE THREAD

**Issue by tobiasfichtner** [matthiasblaesing/netbeans-mantis-integration#37]
I'm trying to add the mantisbt repo over dialog, but there comes no fields to enter values.

on change of provider list to mantisbt will not change previous fields (like mask from bugzilla or else)

log appends, any ideas?

[nb8.2.txt](https://github.com/matthiasblaesing/netbeans-mantis-integration/files/3678889/nb8.2.txt)

**Comment by matthiasblaesing** [comment]
The module depends on JAXB (Java Architecture for XML Binding). It was bundled with the JRE. With JDK9 several modules were removed from the JDK, including JAXB.
I updated the module to bundle JAXB and drop JAXWS dependencies. Attached you find a snapshot build. It would be great if you could test it.

[MantisIntegration-1.6.1-SNAPSHOT.zip](https://github.com/matthiasblaesing/netbeans-mantis-integration/files/3687422/MantisIntegration-1.6.1-SNAPSHOT.zip)

**Comment by tobiasfichtner** [comment]
looks good so fast, let me try final.
![grafik](https://user-images.githubusercontent.com/52255158/66168232-fd15c780-e63c-11e9-8922-e4f9c64c7cad.png)

**Comment by tobiasfichtner** [comment]
Finaly not working

IDE Log:
java.lang.ClassNotFoundException: javax.xml.soap.SOAPException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:222)
Caused: java.lang.ClassNotFoundException: javax.xml.soap.SOAPException starting from ModuleCL@1699352f[eu.doppel_helix.netbeans.MantisIntegration] with possible defining loaders [ModuleCL@2832b531[org.netbeans.modules.websvc.jaxws21api]] and declared parents [org.netbeans.MainImpl$BootClassLoader@5d099f62, ModuleCL@5e1b0f01[org.openide.dialogs], ModuleCL@4d624a09[org.openide.windows], ModuleCL@75eb1bc1[org.netbeans.modules.bugtracking], ModuleCL@1f769ae3[org.openide.awt], Netigso[reference:file:ide/modules/org-apache-commons-logging.jar], ModuleCL@6042d482[org.openide.nodes]]
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:224)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
Caused: java.lang.NoClassDefFoundError: javax/xml/soap/SOAPException
	at org.apache.axis.configuration.FileProvider.configureEngine(FileProvider.java:179)
	at org.apache.axis.AxisEngine.init(AxisEngine.java:172)
	at org.apache.axis.AxisEngine.<init>(AxisEngine.java:156)
	at org.apache.axis.client.AxisClient.<init>(AxisClient.java:52)
	at org.apache.axis.client.Service.getAxisClient(Service.java:104)
	at org.apache.axis.client.Service.<init>(Service.java:113)
	at biz.futureware.mantisconnect.MantisConnectLocator.<init>(MantisConnectLocator.java:12)
	at eu.doppel_helix.netbeans.mantisintegration.repository.MantisRepository.initClient(MantisRepository.java:111)
	at eu.doppel_helix.netbeans.mantisintegration.repository.MantisRepository.getClient(MantisRepository.java:364)
	at eu.doppel_helix.netbeans.mantisintegration.repository.MasterData.getFilters(MasterData.java:247)
	at eu.doppel_helix.netbeans.mantisintegration.query.MantisQueryController$1.run(MantisQueryController.java:209)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

**Comment by matthiasblaesing** [comment]
There is a missing dependency on the soap-api (which was also removed). Another try. This time I did a smoke test against the Mantis Project issue tracker. I was able to connect and did a simple query, so should work as good as before.

[MantisIntegration-1.6.1-SNAPSHOT.zip](https://github.com/matthiasblaesing/netbeans-mantis-integration/files/3692020/MantisIntegration-1.6.1-SNAPSHOT.zip)

You might to remove the installed plugin first.

**Comment by tobiasfichtner** [comment]
Hi, its running on Netbeans8.2 and Netbeans11!

great job, thank you ;) 

if you can, its may be possible to predefine the mantis-basepath as api/soap/mantisconnect.php?WSDL

or is this connector allrdy able to use REST?

Tobias

**Comment by tobiasfichtner** [comment]
ok, its generall running.

A other problem with the Snapshot is after you delete a query and refresh the whole tracker you got a error like this:

![grafik](https://user-images.githubusercontent.com/52255158/66278010-9e06bb80-e8a5-11e9-862c-706ddbc23702.png)


[nb_mantis_Snap_1.6.1.txt](https://github.com/matthiasblaesing/netbeans-mantis-integration/files/3695008/nb_mantis_Snap_1.6.1.txt)

**Comment by matthiasblaesing** [comment]
Should now also be fixed:

[MantisIntegration-1.6.1-SNAPSHOT.zip](https://github.com/matthiasblaesing/netbeans-mantis-integration/files/3699097/MantisIntegration-1.6.1-SNAPSHOT.zip)

In all fairness: I did not test, but from the failure structure, this failure was also present in older versions.

**Comment by tobiasfichtner** [comment]
Hi,

& thank you for your work. The latest does not fix the Problem.

If you delete the last query it is still in the list and if you refresh the querys you get the error message (below).

regards, 
Tobias

**Comment by matthiasblaesing** [comment]
Could you please provide the log of the error? I would have sworn that I tested exactly that case.

**Comment by tobiasfichtner** [comment]
hi & thanks for your support.

after a clean installation (remove all querys, tracker and at least the plugin, restart and re-install the plugin and so on) the error msg does not longer be shown.

as a feature (at last) it will be nice to show in the dialog partial the url from repo like http://<host>/<mantis-basepath>/api/soap/mantisconnect.php?WSDL


king regards,
Tobias
