### ISSUE TITLE
Error Access Mantis with netbeans 18

### ISSUE THREAD

**Issue by itservices-trust** [matthiasblaesing/netbeans-mantis-integration#40]
cannot connect to mantis from netbeans anymore upgrading to netbeans 18 (from 12)
on mantis error log I see the following error anytime I try to access
`[mantisconnect.php] Error Type: ,\nError Description: Creation of dynamic property ADORecordSet_mysqli::$adodbFetchMode is deprecated\nStack Trace:\nadodb.inc.php L1311 __construct(<Object><mysqli_result> (  ), <integer>2)\nadodb.inc.php L1236 _Execute(<string>'SELECT * FROM mantis_user_table WHERE cookie_string=\\'xxxxxx\\'')\nDbQuery.class.php L292 Execute(<string>'SELECT * FROM mantis_user_table WHERE cookie_string=\\'xxxxxx\\'', <array> { [0] => <array> { [0] => 'xxxxxx' } })\nDbQuery.class.php L796 db_execute(<integer>-1, <integer>-1)\ndatabase_api.php L318 compat_db_query(<string>'SELECT * FROM {user} WHERE cookie_string=?', <array> { [0] => 'xxxxxx' }, <integer>-1, <integer>-1, <boolean>true)\nuser_api.php L827 db_query(<string>'SELECT * FROM {user} WHERE cookie_string=?', <array> { [0] => 'xxxxxx' })\nauthentication_api.php L1153 user_get_id_by_cookie(<string>'xxxxxx')\nmc_api.php L529 auth_user_id_from_cookie(<string>'xxxxxx')\nmc_project_api.php L164 mci_check_login(<string>'username', <string>'xxxxxx')\nUnknownFile L? mc_projects_get_user_accessible(<string>'username', <string>'xxxxxx')\nmantisconnect.php L89 handle()\n
`
where "username" is the username used and xxxxxx is the password

EDIT
I've tried to access again using the netbeans version I used before (v 12) and it cannot access anyway, so probably is some kind of update on mantisbt server side (the system has been upgraded from debian 11 to 12)

**Comment by itservices-trust** [comment]
Mantis version 2.25.4

**Comment by matthiasblaesing** [comment]
Thank you for the "Edit". I think your analysis is spot on and here is the explanation:

https://php.watch/versions/8.2/dynamic-properties-deprecated

and here are answers for coders:

https://stackoverflow.com/questions/74878889/php-warning-deprecated-creation-of-dynamic-property-is-deprecated

Reducing the error reporting level for the server might already fix the issue.

**Comment by itservices-trust** [comment]
I tried with
`error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE & ~E_WARNING`
in php.ini for apache2, but still got error connecting.

**Comment by matthiasblaesing** [comment]
Sorry, I would need to do the setup myself to investigate and don't have time for this.

**Comment by itservices-trust** [comment]
I think it is related to Debian 12 that switched from PHP 7.4 to 8.2, so I'll try upgrading Mantis to 2.25.7 and report back.
Thanks

**Comment by itservices-trust** [comment]
Even after upgrading to latest MantisBT stable (2.25.7) the error is still present.
I'll open a Mantis issue.

**Comment by itservices-trust** [comment]
Fixed upgrading ADODB to latest version.

**Comment by matthiasblaesing** [comment]
Thank you for investigating and reporting back!

**Comment by itservices-trust** [comment]
Bug still present.
After upgrading AdoDB on Mantis server, plugin connection could be established correctly, but when trying to create or searching an issue from Netbeans 18 with Mantis plugin we receive this exception:
`AxisFault
 faultCode: {http://schemas.xmlsoap.org/soap/envelope/}Server
 faultSubcode: 
 faultString: Error Type: ,
Error Description: Creation of dynamic property BugData::$bug_text_id is deprecated
 faultActor: 
 faultNode: 
 faultDetail: 
	{http://xml.apache.org/axis/}stackTrace:Error Type: ,
Error Description: Creation of dynamic property BugData::$bug_text_id is deprecated
	at org.apache.axis.message.SOAPFaultBuilder.createFault(SOAPFaultBuilder.java:222)
	at org.apache.axis.message.SOAPFaultBuilder.endElement(SOAPFaultBuilder.java:129)
	at org.apache.axis.encoding.DeserializationContext.endElement(DeserializationContext.java:1087)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:618)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1728)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2899)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
	at org.apache.axis.encoding.DeserializationContext.parse(DeserializationContext.java:227)
	at org.apache.axis.SOAPPart.getAsSOAPEnvelope(SOAPPart.java:696)
	at org.apache.axis.Message.getSOAPEnvelope(Message.java:435)
	at org.apache.axis.handlers.soap.MustUnderstandChecker.invoke(MustUnderstandChecker.java:62)
	at org.apache.axis.client.AxisClient.invoke(AxisClient.java:206)
	at org.apache.axis.client.Call.invokeEngine(Call.java:2784)
	at org.apache.axis.client.Call.invoke(Call.java:2767)
	at org.apache.axis.client.Call.invoke(Call.java:2443)
	at org.apache.axis.client.Call.invoke(Call.java:2366)
	at org.apache.axis.client.Call.invoke(Call.java:1812)
	at biz.futureware.mantisconnect.MantisConnectBindingStub.mc_issue_get(MantisConnectBindingStub.java:2131)
	at eu.doppel_helix.netbeans.mantisintegration.repository.MantisRepository.updateIssueFromRepository(MantisRepository.java:377)
	at eu.doppel_helix.netbeans.mantisintegration.issue.MantisIssue.refresh(MantisIssue.java:113)
	at eu.doppel_helix.netbeans.mantisintegration.repository.MantisRepository.getIssues(MantisRepository.java:226)
	at eu.doppel_helix.netbeans.mantisintegration.repository.MantisRepository.getIssues(MantisRepository.java:216)
	at eu.doppel_helix.netbeans.mantisintegration.query.MantisQueryController$6.run(MantisQueryController.java:485)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)
	{http://xml.apache.org/axis/}hostname:xxx-hp
Error Type: ,
Error Description: Creation of dynamic property BugData::$bug_text_id is deprecated
	at org.apache.axis.message.SOAPFaultBuilder.createFault(SOAPFaultBuilder.java:222)
	at org.apache.axis.message.SOAPFaultBuilder.endElement(SOAPFaultBuilder.java:129)
	at org.apache.axis.encoding.DeserializationContext.endElement(DeserializationContext.java:1087)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:618)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1728)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2899)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
	at org.apache.axis.encoding.DeserializationContext.parse(DeserializationContext.java:227)
	at org.apache.axis.SOAPPart.getAsSOAPEnvelope(SOAPPart.java:696)
	at org.apache.axis.Message.getSOAPEnvelope(Message.java:435)
	at org.apache.axis.handlers.soap.MustUnderstandChecker.invoke(MustUnderstandChecker.java:62)
	at org.apache.axis.client.AxisClient.invoke(AxisClient.java:206)
	at org.apache.axis.client.Call.invokeEngine(Call.java:2784)
	at org.apache.axis.client.Call.invoke(Call.java:2767)
	at org.apache.axis.client.Call.invoke(Call.java:2443)
	at org.apache.axis.client.Call.invoke(Call.java:2366)
	at org.apache.axis.client.Call.invoke(Call.java:1812)
	at biz.futureware.mantisconnect.MantisConnectBindingStub.mc_issue_get(MantisConnectBindingStub.java:2131)
	at eu.doppel_helix.netbeans.mantisintegration.repository.MantisRepository.updateIssueFromRepository(MantisRepository.java:377)
	at eu.doppel_helix.netbeans.mantisintegration.issue.MantisIssue.refresh(MantisIssue.java:113)
	at eu.doppel_helix.netbeans.mantisintegration.repository.MantisRepository.getIssues(MantisRepository.java:226)
	at eu.doppel_helix.netbeans.mantisintegration.repository.MantisRepository.getIssues(MantisRepository.java:216)
	at eu.doppel_helix.netbeans.mantisintegration.query.MantisQueryController$6.run(MantisQueryController.java:485)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)
Caused: java.lang.RuntimeException
	at eu.doppel_helix.netbeans.mantisintegration.repository.MantisRepository.updateIssueFromRepository(MantisRepository.java:385)
	at eu.doppel_helix.netbeans.mantisintegration.issue.MantisIssue.refresh(MantisIssue.java:113)
	at eu.doppel_helix.netbeans.mantisintegration.repository.MantisRepository.getIssues(MantisRepository.java:226)
	at eu.doppel_helix.netbeans.mantisintegration.repository.MantisRepository.getIssues(MantisRepository.java:216)
[catch] at eu.doppel_helix.netbeans.mantisintegration.query.MantisQueryController$6.run(MantisQueryController.java:485)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)`

**Comment by itservices-trust** [comment]
Applying the following patch seems to fix the issue:
https://github.com/mantisbt/mantisbt/commit/0ba485e0821c6009f935304eb99b9d7426887e0f
I'll report back.
